### ISSUE TITLE
Notes with a "missed" rename are lost from the program

### ISSUE THREAD

**Issue by dgraziotin** [glushchenko/fsnotes#114]
Steps to reproduce.

1. Create a note, any title will do (let's call it **tets**).
2. Write anything in the note (asdasdasd).
3. Realize that the title **tets** has a typo. Should be **test**.
4. Select the note and hit _Rename_ for renaming it to **test**.
5. Miss renaming the note and click either on the main window pane or on an empty space on the notes list.
6. The note disappears from the program. It is replaced by a "Untitled Note X" one if the accidental click is made on the main window pane.
7. tets.md is still present in the storage path, but not present in FSnotes
8. Restarting FSnotes does not bring the note back.

FSNotes Version 1.2.8 (95)

**Comment by glushchenko** [comment]
Fixed. Did you try 1.2.9?

**Comment by dgraziotin** [comment]
I have just tried it right now. The issue is still there but it seems that it was released before your fix?

**Comment by glushchenko** [comment]
I dont know how to reproduce :/

**Comment by gingerbeardman** [comment]
Easiest way to reproduce:

1. Cmd+N
2. Cmd+R
3. ESC

**Comment by glushchenko** [comment]
> The issue is still there but it seems that it was released before your fix?

Yep. Released in 1.2.10 ;)

**Comment by gingerbeardman** [comment]
Still broken.

**Comment by gingerbeardman** [comment]
Also, if I do:

1. cmd+N
2. cmd+R
3. click into Note

Note is kept in sidebar but the number X in the name "Untitled Note X" increments every time I dismiss the renaming.

**Comment by gingerbeardman** [comment]
Video: https://youtu.be/s60ri1x6v9Q

**Comment by glushchenko** [comment]
Please redownload build 101

**Comment by gingerbeardman** [comment]
Still a problem :(

1. cmd+N
2. cmd+R
3. click into Note
repeat

results in duplicate Untitled Notes X appearing

![screen shot 2018-02-22 at 20 28 25](https://user-images.githubusercontent.com/49612/36562443-f54c5d00-180e-11e8-9315-a92903379c9c.png)

**Comment by glushchenko** [comment]
Arrr, now i reproduced it. Will patch tomorrow.

**Comment by glushchenko** [comment]
@gingerbeardman checkout build 101 :)

**Comment by gingerbeardman** [comment]
Looks good to me
