### ISSUE TITLE
Notes List is reset on launch when sidebar is hidden

### ISSUE THREAD

**Issue by cvn** [glushchenko/fsnotes#1682]
### Description

When the sidebar is hidden, quitting and relaunching the app will forget which notes were shown in the Notes List. This started happening in 6.6.4. In 6.6.3, the Notes List shows the same notes after relaunch.

### To Reproduce

1. Select Inbox in the Sidebar
2. See that only the notes from the Inbox are shown in the Notes List
3. View > Hide Sidebar
4. Quit the app
5. Launch the app
6. See the Note List showing every file in FSNotes, not just the Inbox notes

### Expected behavior

The Notes List should be preserved when relaunching the app.

### FSNotes version

6.6.5

### macOS/iOS version

macOS 14.2.1

### Additional context

Thank you!

**Comment by glushchenko** [comment]
Fixed

**Comment by cvn** [comment]
Hello. Is the fix in a release yet?

I tested in 6.9.5 and this issue persists.
