### ISSUE TITLE
No jumping Icon when starting FSNotes

### ISSUE THREAD

**Issue by helmut72** [glushchenko/fsnotes#422]
There is no jumping Icon when starting FSNotes. Tested on 2 different Macs and at least since early 2.x version. Is this normal?

**Comment by gingerbeardman** [comment]
How long does your FSNotes take to startup?

Mine is full loaded and usable in a fraction of a second.

**Comment by helmut72** [comment]
Starting is fast, that's not the problem. I only ask, because 99.9% of other macOS Apps does have bouncing dock icons. From starting speed, it should at least bounce twice 😊

**Comment by helmut72** [comment]
It's easy to test against: create new macOS project in Xcode, press run in Xcode, move icon to the left in Dock that it is persistent, stop in Xcode, restart from Dock. Result: one bouncing icon

I'm on Mac since 10 years and can't remember this behavior from other apps. That's the reason I've asked. It's not a showstopper or a bug, but so much different that I need to ask 😊

**Comment by glushchenko** [comment]
Hmm, interesting. Some apps jumping, some not (i.e 1password).

**Comment by glushchenko** [comment]
Fixed :-)

**Comment by helmut72** [comment]
1Password is also jumping on both of my Macs ;-) Maybe you have disabled this option in the Dock settings.

Thanks for the fast fix :-)

**Comment by gingerbeardman** [comment]
This is not fixed.

Now, the app icon does not jump during launch, but jumps after launch.

This is not the desired behaviour and in fact creates another problem, #427

**Comment by gingerbeardman** [comment]
I think the icon does not bounce because the app has `LSUIElement: true` in the plist. This means that it is an app without any dock icon. I guess that was added as part of the feature that required the need for an option "Show icon in dock".

**Comment by glushchenko** [comment]
Fixed in 2.5.1

**Comment by gingerbeardman** [comment]
Works for me in the updated version 2.5.1 (206)

**Comment by helmut72** [comment]
Works also for me, thanks 👍
