### ISSUE TITLE
Focus jumps into a note inadvertently when typing a search string quickly

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#527]
_(Created this issue based on [my earlier comment](https://github.com/glushchenko/fsnotes/issues/518#issuecomment-471799408) to #518, since others seem to be experiencing it.)_

The focus jumps into a note inadvertently when typing a search string quickly:

1. I invoke FSNotes with my global search shortcut.
2. I type a few search words quickly.
3. After a few characters the focus moves into the last visible note and my typing goes into the note.

I'll try to express this as an example, searching for `my search words`:

After invoking FSNotes, I start typing in the search bar:

    🔍[my sea             ]

Then, somewhere in the note, this appears:

    rch words

That would be expected behavior if I had hit enter or tab after "*my sea*", but I didn't. This is not easy to reproduce, but it does seem more likely to occur if I'm typing fast, with the search results stuttering to appear. This only began sometime in the last few updates.

FWIW, I also had this experience when using nvAlt, although it happened there much more frequently. It's one of the reasons I stopped using nvAlt.

**Comment by peavine** [comment]
I have experienced the same exact issue and thought I should add/confirm a few miscellaneous points:

* I don't use the global search shortcut at any time.

* I have a capable 2018 Mac mini running Mojave.

* This behavior happens almost exclusively when I quickly type one or more words in the search or create bar. I don't recall encountering this issue when typing slowly.

* I use the search or create bar almost exclusively to create new notes. I mention this because I think (but am not sure) the issue occurs when the Note List is empty and I am typing the name of the new note.

**Comment by glushchenko** [comment]
Preferences -> Editor -> "Focus in editor when selecting note" is enabled?

**Comment by peavine** [comment]
I always have the focus-in-editor preference enabled.

BTW, I encountered this issue just a few minutes ago. I then repeated the exact same keystrokes and did not encounter the issue. I suspect it's hard to fix when you can't reliably reproduce the behavior.

**Comment by glushchenko** [comment]
I think thats fixed by commit above

**Comment by peavine** [comment]
I have not encountered this issue since the commit noted above. Thanks.

**Comment by quinncomendant** [comment]
I'm sorry to say I have been experiencing this issue frequently today. It's not fixed yet. I'm using version 3.0.4 (259).

**Comment by glushchenko** [comment]
Can you provide steps for reproduction?

**Comment by quinncomendant** [comment]
FYI this is still happening to me. It's intermittent, so I can't offer steps to reproduce it.

I think the problem is related to auto-search-while-typing. Today I noticed that when focus jumps into a note, focus goes to the position where the previewed search result is highlighted. 

Is there a way to disable auto-search-while-typing? I think that would be a workaround for this issue. Of course, I guess that would require setting two keys for acting on the entered search query: one for "submit search query" and another for "create note using this search query as the title".

**Comment by glushchenko** [comment]
T

**Comment by gingerbeardman** [comment]
I also get this occasionally and had reported another issue about it (sorry, too lazy right now to search for it)

**Comment by glushchenko** [comment]
@quinncomendant can you try to disable this option?
 
![image](https://user-images.githubusercontent.com/1089917/107854638-e3d27d00-6e25-11eb-8059-238b0f68b981.png)

Do you experience it with disabled option?

**Comment by glushchenko** [comment]
I'm checked all twice. All places when focus triggered is:

1. Window resize
2. Tab or return pressed
3. Mouse click on note cell view in table
4. ⌘-j and ⌘+k shortcuts 
5. Note creation

**Comment by quinncomendant** [comment]
> @quinncomendant can you try to disable this option?
> Do you experience it with disabled option?

Yes, I have always had that option disabled. 

<img width="476" alt="Screen Shot 2021-02-13 at 15 37 33" src="https://user-images.githubusercontent.com/6884276/107862556-f8594a00-6e12-11eb-867f-a0d061f72a43.png">

**Comment by glushchenko** [comment]
Please try FSNotes 5

**Comment by quinncomendant** [comment]
I still have this problem every day. The result is that my note files are receiving some keystrokes intended for the search bar, and many of my notes have deleted text and inserted half-words. I just went through my git diff history, and found dozens of notes that were broken, and had to restore their content and clean them. I can't use FSNotes now because of this liability. I'm sorry.
