### ISSUE TITLE
Hide/Show sidebar - Sidebar is not restored from hidden view

### ISSUE THREAD

**Issue by magicnemo** [glushchenko/fsnotes#543]
Hi!

Thanks for a great app! 
In version 2.9.5 aswell as 3.0 beta, whenever I hide notelist (using Cmd+shift+B) or selecting via meny, it minimizes ok, but when a try to restore it, nothing happends.
I just see a vertical scrollbar to the left, and have to manually restore the sidebar by manually increase its size using mouse.

It has been working in earlier versions, perhaps a faulty setting or something? 

BR Anders

**Comment by peavine** [comment]
I couldn't reproduce this issue but I then noticed that my Note List doesn't have a vertical scroll bar. I reduced the height of FSNotes until the vertical scroll bar became visible, and I then encountered the issue.

FSNotes 3.0.0 (244)

**Comment by glushchenko** [comment]
Please try last build.

**Comment by peavine** [comment]
I installed FSNotes build 248 and I still have this issue exactly as before.

BTW, the thread title shows that the issue is with the sidebar but @magicnemo shows in the text of his post that the issue is with the Note List. The issue I'm having is with the Note List--hiding and showing the sidebar works fine.

**Comment by magicnemo** [comment]
Hi! I just latest version on github tried version 3.0.0 (247) (as indicated in FS notes "About" windows).

I agree with peavine, the problem still exists, 
As soon as you get a scroll bar to the right of the note list, if you then enter a note and press cmd+shift+b, the note list  minimizes ok, but pressing cmd+shift+b does not recover the note list.

If you dont see a scrollbar to right of notelist, i.e. either not so many notes in the folder or if you have entered a search string/filter to minimize # of notes in note list, everything works ok (minimizing and expanding) with cmd+shift+b

**Comment by glushchenko** [comment]
Please re-download rc1

**Comment by magicnemo** [comment]
Now using 3.0.0 (249)

Still same problem unfortunately. Is it possible that a config-file or something needs to be deleted before installing a new version?

**Comment by glushchenko** [comment]
What macOS version did you use?

**Comment by peavine** [comment]
I'm using macOS Mojave (10.14.4) with all updates and FSNotes 3.0.0 (249). 

I just checked and the issue remains with both the sidebar and note list.

**Comment by glushchenko** [comment]
I dont know how to reproduce, sorry. Can you record video?

**Comment by peavine** [comment]
I've uploaded a video. I seem to have misplaced the app I used before, so I recorded the video in quicktime and converted it to an animated gif with a utility. I hope this is visible OK.

![Screen Recording 2019-04-29 at 1 57 06 PM mov](https://user-images.githubusercontent.com/35905279/56927206-730f7480-6a88-11e9-9f2b-ca34a71d6351.gif)

**Comment by glushchenko** [comment]
Ahh, in my settings scroll bar not showed always, and all works fine accordingly ...

![image](https://user-images.githubusercontent.com/1089917/56930484-7edd5400-6ae5-11e9-816d-157e03350459.png)

**Comment by glushchenko** [comment]
Fixed I think :)

**Comment by glushchenko** [comment]
Please checkout v3

**Comment by peavine** [comment]
I installed build 254 and I still have the issue (see screen video below). 
![Screen Recording 2019-04-30 at 7 39 29 AM mov](https://user-images.githubusercontent.com/35905279/56971177-9df7d800-6b1d-11e9-96e0-81b344f49c71.gif)

**Comment by peavine** [comment]
FWIW, the following is a screenshot of my macOS preferences.
<img width="668" alt="Screenshot 04 30 19 at 07 56 32" src="https://user-images.githubusercontent.com/35905279/56971376-f5964380-6b1d-11e9-86e5-e5d3d441b321.png">

**Comment by glushchenko** [comment]
@magicnemo can you confirm @peavine report?

Guys, I am really don't know ho to reproduce this :( Scrollbar does not exist on my macOS.

**Comment by peavine** [comment]
As a practical matter, this is not an issue that has any impact on me day to day. Since it affects only a few people, and because it may have something to do with our computer setup, I would be in favor of closing this issue.

**Comment by magicnemo** [comment]
Hi, just tried 254 aswell, I can confirm "hide/show note list" toggle now works every time! 👍

But "hide/show sidebar" is just like peavine says, it works when you have all content / folders visable in window, if some are hidden below window & scrollbar i shown, it wont recover from hidden view (unless drag window size with mouse).

But I agree with peavine, its a minor

for info
Attaching a picture below how my sidebar looks like, pressing shortcut for hide sidebar in that state will make it stuck there..
![image](https://user-images.githubusercontent.com/5127420/57008097-00200e00-6bee-11e9-8a43-d7d92f18a3c7.png)

**Comment by glushchenko** [comment]
Holy shit, its not minor 😳

**Comment by magicnemo** [comment]
Please note, its the left most window i am talking about, in the picture the sidebar looks fine, its when trying to hide it and then recovee it wont work

I.e **dont look at the right side of the picture**, i intentionally cut parts of the picture with my note contents

**Comment by peavine** [comment]
I'm currently using build 254 downloaded from the App Store. As noted by @magicnemo, this issue no longer impacts the note list. Also, I do not experience this issue at all if I change the macOS preference setting from 

"Show scroll bars Automatically based on mouse or trackpad"

to

"Show scroll bars Always"

I have included a video of FSNotes with the "Show scroll bars Always" preference option enabled. You will note that the sidebar toggles off and on as expected and that the scroll bars disappear on inaction. 

BTW, I consider this issue to be minor in that it only affects a very few users and could result from the computer setup of those users.

![Screen Recording 2019-05-01 at 6 53 43 AM mov](https://user-images.githubusercontent.com/35905279/57021216-6f8f0100-6be0-11e9-8ee6-44c0fdbbb85a.gif)

**Comment by glushchenko** [comment]
Good

**Comment by magicnemo** [comment]
Yes I agree, if I also change Mac setting to "Show Scrollbars" to always the problem is gone. 
Rather spend time on other things like double click a picture to show it in bigger screen / open it in preview  :) 
We can close this one at least from my side

**Comment by glushchenko** [comment]
You can click picture for open in Finder and cmd-click to change title, but thats good point, will be added soon

**Comment by magicnemo** [comment]
Ok thanks! :) Again, great work / app, use it every day! 👍
