### ISSUE TITLE
Cannot show images with encoded path

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#715]
**Describe the bug**

`![](assets/Screen%2520Shot%25202019-01-31%2520at%252014.00.57.png)` shows up as a missing image

**To Reproduce**
1. Find an image with whitespace in the filename (as created by the macOS screen shot feature)
2. Drag it into a note
3. Toggle the preview off an on

**Expected behavior**
A preview of the image is displayed.

**Actual behavior**
The image shows up when first adding it, but disappears the next time the preview is rendered.

**Workaround**
Don't use spaces in file names.

**Desktop:**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version: 3.9.1

**Additional context**
Looking at the note in an external editor I saw a correct image link, with the spaces in the filename URL-encoded as `%20`. It seems that FSNotes cannot reverse its own encoding.

**Comment by glushchenko** [comment]
Thanks, fixed

**Comment by tewe** [comment]
Your fix seems to stop encoding URLs inserted by FSNotes. But it still wouldn't be able to preview encoded URLs that were imported, pasted or even typed manually, right?

**Comment by glushchenko** [comment]
All images and file names should be encoded. If not — preview will not work

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tewe** [comment]
I'm afraid it still doesn't work. The following textbundle was created by dragging images into FSNotes 4.0.12. They all show up fine in https://marked2app.com but not at all in FSNotes.

```markdown
![Apple Notes Print Dialog](assets/Notes%20Print%20Scale%20to%20Percentage.png)

![Apple Notes Preset Dialog](assets/Notes%20Preset%20Scale%20to%20Percentage.png)

![](assets/Preview%20Preset%20Scale%20to%20Image.png)

![](assets/Preview%20Preset%20Scale%20to%20Percentage.png)

![](assets/Preview%20Print%20Scale%20to%20Image.png)

![](assets/Preview%20Print%20Scale%20to%20Percentage.png)
```

**Comment by glushchenko** [comment]
Fixed in 4.0.15

**Comment by tewe** [comment]
With 4.0.15 the images show up while editing (when at least I would prefer the Markdown instead) and still do not show up in the preview.

**Comment by glushchenko** [comment]
Please provide test file, I can not reproduce this.

**Comment by tewe** [comment]
I can easily reproduce it by dragging a screenshot into FSNotes, or using the snippet above. Here is a [compressed text bundle](https://github.com/glushchenko/fsnotes/files/4046940/bundle.zip).

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/4.0.16/FSNotes_4.0.16_dev.zip

**Comment by tewe** [comment]
That build does show images in preview! They have a context menu with "Open Image in New Window", which does nothing. Images also still show up when editing, making it impossible to edit e.g. the alternative text in their Markdown.

**Comment by glushchenko** [comment]
Use ⌘ + mouse click on images for editing Title

**Comment by tewe** [comment]
Cmd+click works. Thanks for fixing this.

But I believe that any attempt at rich text editing of Markdown is misguided. So now that FSNotes is looking more like Bear I'll start looking for an alternative.
