### ISSUE TITLE
Wiki link and Ability to "go back"

### ISSUE THREAD

**Issue by jakemkc** [glushchenko/fsnotes#882]
**Describe your feature request**
Recently FSNotes has improved the usability of wiki link. However, after you click into the wiki link, there is no easy way to go back to the file that you were working on.

[Question]
I wonder could there be a way to do the go back?

[Suggestions]
1. It could be something similar to the "go back" function of a browser that you can go back more than 1 step. 

2. Or it could be in a simpler way: after clicking into the link, if you press "esc" once, it will clear the search term and the cursor stays at the search box (this is how FSNotes behaves now); if you press "esc" twice, it will select the file previously working on before a search?

 
**Additional context**
1. The feature is requested for MacOS version of FSNotes.
2. I am referring to the internal wiki links (e.g. [[hello]]) instead of html links.

**Comment by glushchenko** [comment]
Fixed, thanks.

**Comment by glushchenko** [comment]
Hi, @jakemkc, please try https://github.com/glushchenko/fsnotes/releases/tag/4.3.0

**Comment by jakemkc** [comment]
Just tried 4.3.0. 

The search box at the top of the note list is gone and replaced with a new note button; also the wiki links are not working (i.e. It won't do a search for that title and show me the file)

maybe a bug or is it just me getting this issue?

<img width="1099" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/18485734/81502286-10f86a80-92ab-11ea-9432-bae56e3188fe.png">

**Comment by glushchenko** [comment]
WikiLinks not search now, instead refers to a file.

New note icon seems line a bug. macOS version?

Thanks

**Comment by jakemkc** [comment]
I see. 

Currently using MacOS 10.14.6

**Comment by glushchenko** [comment]
Of course you can, why no?

Button position fixed in 4.3.1, available in Releases.

**Comment by jakemkc** [comment]
Thanks for the quick release. Tried 4.3.1 and it seems still having issues.

1) I can't create a new note through wiki link. It simply put the current note name into the search box after clicking on the wiki link.

![1](https://user-images.githubusercontent.com/18485734/81511192-7ff2b500-92e5-11ea-9b00-75211d9d2d53.gif)

<BR>

2) If I click on the wiki link pointing to an existing note, it works and bring me to it directly without any input appears in the search box. However, if I click "esc", it brings me to the search box field. How can I go back to the previous note with the wiki link?

![2](https://user-images.githubusercontent.com/18485734/81511196-83863c00-92e5-11ea-98c5-2dfc736b57b9.gif)

**Comment by glushchenko** [comment]
@jakemkc please check https://github.com/glushchenko/fsnotes/releases/download/4.3.2/FSNotes_4.3.2.zip

Back and forward history available by shortcuts ⌘ + shift + [ and ⌘ + shift + ]

**Comment by sloria** [comment]
Confirmed that  ⌘ + shift + [ and ⌘ + shift + ] are working correctly on 4.3.2.

**Comment by jakemkc** [comment]
great, it works now!
