### ISSUE TITLE
Swedish characters does not work i search field with auto-completion

### ISSUE THREAD

**Issue by Aetles** [glushchenko/fsnotes#989]
**Describe the bug**
When typing Swedish characters å, ä and ö in the search field you can't get past it without it being removed if there is auto-completion available and it can't be entered multiple times.

**To Reproduce**
1. Put a word with international characters like å, ä or ö in a note title. (Example: hårddisk, luftvärmepump.)
2. Start typing the word in the search field to trigger the auto-completion of the title. 

**Expected behavior**
That the international characters works like any other ASCII characters.

**Actual behavior**
When the international character is reached, and *if* there is auto-completion in the search field, the character can't be entered multiple times and when the next character is entered the international character is removed, causing the search to fail.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version: 4.7.1

**Additional context**
I have a faint memory of this bug happening before, but being fixed.

**Comment by glushchenko** [comment]
I can not reproduce it, can you provide video?

**Comment by Aetles** [comment]
Here is a quick example, I'm trying to type the word of the title. 

![FSNotes with character issues](https://user-images.githubusercontent.com/429202/96042176-4feba700-0e6d-11eb-9384-dc545790d395.gif)

**Comment by glushchenko** [comment]
Interesting, trying Catalina and Virtualbox with installed High Sierra. 

Swedish keyboard, chars with umlaut – åöä

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1089917/96270630-93acf080-0fd4-11eb-90ea-09dc00e701de.png">

Video:

![Screen Recording 2020-10-16 at 17 36 53 2020-10-16 17_38_27](https://user-images.githubusercontent.com/1089917/96272188-737e3100-0fd6-11eb-9fe6-c07658b31fc3.gif)

**Comment by glushchenko** [comment]
Do you have any idea why this is happening?

**Comment by Aetles** [comment]
No idea right now, but it could be something in my environment, I'll try to troubleshoot it, turning of extensions, loggin in as another user etc and see if I can pinpoint the cause.

**Comment by glushchenko** [comment]
Thanks, @Aetles. I really appreciate any help related to bug reports.

**Comment by Aetles** [comment]
This is the old bug that I was remembering, btw: https://github.com/glushchenko/fsnotes/issues/248

**Comment by glushchenko** [comment]
I remember, but this was fixed long times ago.

**Comment by bonny** [comment]
I have the same problem. In my testing the problem always occur when the actual filename has chars like "åäö" in it but not if the filename does not contain any of those chars.

So if a file named `dåååå.md` has contents `# dåååå` then I can't search correctly for it.
But if the file is named `daaaa.md` with same contents `# dåååå` then I can search for it.

Also the error only occurs if I have the settings "[x] First line a title" checked.

Can maybe @Aetles check if this seems to be the same problem?

**Comment by Aetles** [comment]
Oh that's an interesting theory, I still have the problem but I didn't think of file names. I'll check and get back!

**Comment by Aetles** [comment]
First, I don't use "First line as title" but still see the issue. 

Second, my file names have Swedish characters since it is the same as titels. I did change the file name but then the title also changes so I don't trigger the issue. 

Third, the dots above the a look extra weird when it's triggered:

![Skärmavbild 2021-01-18 kl  20 51 03@2x](https://user-images.githubusercontent.com/429202/104957844-322f6000-59cf-11eb-969d-68c55705d5aa.png)

**Comment by bonny** [comment]
I wrote that wrong: I mean that I don't get that error if the "First line a title"-checkbox is checked. But I also don't normally have that checked.

Regarding the file names I changed the names using Finder so I did not rename them in FSNotes, so that way the file name was completely different from the note contents. But yes then the title gets wrong, but still maybe a hint that that could be the cause of the error.

**Comment by glushchenko** [comment]
Finally reproduced and fixed 🥳

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/4.9.7/FSNotes_4.9.7.zip

**Comment by Aetles** [comment]
I've tested and yes, it seems to fix it!
